# Generated by Django 2.2.6 on 2019-10-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localusers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalUser',
        ),
    ]
